# -*- coding: utf-8 -*-
"""NeurOGrasp_RealDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2jekkaVQKzGBSYoq2VmV1q-cA2J2_tq

# 🤖⚡ NeurOGrasp — Real Dataset Edition
## Transparent Object Grasping with Spiking Neural Networks + Event Camera
### Using YOUR 100-image transparent glass dataset (Pascal VOC annotations)

---

| Step | Topic |
|------|-------|
| 1 | Setup & GPU Check |
| 2 | Load Real Dataset (JPG + XML) |
| 3 | Dataset Explorer & Statistics |
| 4 | Event Camera Simulation (v2e) |
| 5 | Voxel Grid Encoding |
| 6 | SNN Architecture (LIF + Temporal Attention) |
| 7 | Loss Functions |
| 8 | Training Pipeline |
| 9 | Training Curves & Analysis |
| 10 | Inference on Real Images |
| 11 | Grasp Visualisation |
| 12 | Ablation Study |
| 13 | Results Summary |

> **Dataset**: 100 real transparent glass images with Pascal-VOC bounding-box labels  
> **Runtime**: Colab T4 GPU recommended — `Runtime → Change runtime type → T4`

## Step 1: Install Dependencies & Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install torch torchvision torchaudio -q
# !pip install opencv-python-headless matplotlib tqdm numpy lxml albumentations -q

import os, glob, random, time, zipfile, warnings
import xml.etree.ElementTree as ET
from pathlib import Path
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional
from collections import defaultdict

import numpy as np
import cv2
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from tqdm.notebook import tqdm

warnings.filterwarnings('ignore')
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print('=' * 58)
print('  NeurOGrasp — Real Dataset Edition')
print('=' * 58)
print(f'  PyTorch  : {torch.__version__}')
print(f'  Device   : {device}')
if torch.cuda.is_available():
    print(f'  GPU      : {torch.cuda.get_device_name(0)}')
    print(f'  VRAM     : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')
print(f'  NumPy    : {np.__version__}')
print(f'  OpenCV   : {cv2.__version__}')
print('=' * 58)
print('✅ Environment ready!')

"""## Step 2: Load Real Dataset (JPG + Pascal VOC XML)

Upload your `archive.zip` to Colab, then run this cell to extract and parse it.

**Expected structure inside archive.zip**:
```
transparent_glass/transparent_glass/*.jpg   ← 100 images
annotations/annotations/*.xml               ← 100 Pascal VOC label files
```
"""

# ─── Extract archive ──────────────────────────────────────────────────────
ZIP_PATH  = 'archive.zip'   # change if your file has a different name
EXTRACT   = 'data/raw'

os.makedirs(EXTRACT, exist_ok=True)

if os.path.exists(ZIP_PATH):
    print(f'Extracting {ZIP_PATH} ...')
    with zipfile.ZipFile(ZIP_PATH, 'r') as z:
        z.extractall(EXTRACT)
    print('✅ Extraction complete')
else:
    print(f'⚠️  {ZIP_PATH} not found in current directory.')
    print('   Upload archive.zip to Colab via the Files panel, then re-run.')

# Auto-discover image and annotation directories
img_candidates  = glob.glob(f'{EXTRACT}/**/*.jpg', recursive=True)
xml_candidates  = glob.glob(f'{EXTRACT}/**/*.xml', recursive=True)
print(f'Found {len(img_candidates)} JPG images')
print(f'Found {len(xml_candidates)} XML annotations')

# ─── Pascal VOC XML Parser ────────────────────────────────────────────────
def parse_voc_xml(xml_path: str) -> Dict:
    """Parse a Pascal-VOC XML annotation file."""
    tree = ET.parse(xml_path)
    root = tree.getroot()

    size_el = root.find('size')
    W = int(float(size_el.find('width').text))
    H = int(float(size_el.find('height').text))

    boxes, labels = [], []
    for obj in root.findall('object'):
        # label tag is <n> in this dataset
        name_el = obj.find('n') or obj.find('name')
        label   = name_el.text.strip() if name_el is not None else 'transparent_glass'
        bb = obj.find('bndbox')
        xmin = float(bb.find('xmin').text)
        ymin = float(bb.find('ymin').text)
        xmax = float(bb.find('xmax').text)
        ymax = float(bb.find('ymax').text)
        boxes.append([xmin, ymin, xmax, ymax])
        labels.append(label)

    return {'width': W, 'height': H, 'boxes': boxes, 'labels': labels}


# ─── Build paired dataset list ────────────────────────────────────────────
xml_dir = Path(xml_candidates[0]).parent if xml_candidates else None
img_dir = Path(img_candidates[0]).parent if img_candidates else None

pairs = []
for xml_path in xml_candidates:
    stem     = Path(xml_path).stem
    img_path = img_dir / (stem + '.jpg')
    if img_path.exists():
        pairs.append({'img': str(img_path), 'xml': xml_path})

print(f'✅ Matched {len(pairs)} image-annotation pairs')

# Parse all annotations
annotations = [parse_voc_xml(p['xml']) for p in pairs]

# Verify
sample = annotations[0]
print(f'\nSample annotation:')
print(f'  Image size : {sample["width"]} × {sample["height"]}')
print(f'  Objects    : {len(sample["boxes"])}')
print(f'  Labels     : {sample["labels"]}')
print(f'  Boxes      : {sample["boxes"]}')

"""## Step 3: Dataset Explorer & Statistics"""

# ─── Dataset statistics ───────────────────────────────────────────────────
all_labels   = [l for ann in annotations for l in ann['labels']]
obj_counts   = [len(ann['boxes'])  for ann in annotations]
img_widths   = [ann['width']       for ann in annotations]
img_heights  = [ann['height']      for ann in annotations]

box_areas, box_aspects = [], []
for ann in annotations:
    W, H = ann['width'], ann['height']
    for xmin, ymin, xmax, ymax in ann['boxes']:
        bw = xmax - xmin
        bh = ymax - ymin
        box_areas.append((bw * bh) / (W * H))   # normalised area
        if bh > 0:
            box_aspects.append(bw / bh)

from collections import Counter
label_counts = Counter(all_labels)

print('─' * 45)
print('  Dataset Statistics')
print('─' * 45)
print(f'  Total images      : {len(pairs)}')
print(f'  Total objects     : {len(all_labels)}')
print(f'  Classes           : {dict(label_counts)}')
print(f'  Avg obj/image     : {np.mean(obj_counts):.2f}')
print(f'  Max obj/image     : {max(obj_counts)}')
print(f'  Avg box area      : {np.mean(box_areas)*100:.1f}% of image')
print(f'  Avg aspect ratio  : {np.mean(box_aspects):.2f} (w/h)')
print(f'  Image widths      : {min(img_widths)}–{max(img_widths)} px')
print(f'  Image heights     : {min(img_heights)}–{max(img_heights)} px')
print('─' * 45)

# ─── Visualise 8 sample images with ground truth boxes ────────────────────
fig, axes = plt.subplots(2, 4, figsize=(18, 9))
fig.patch.set_facecolor('#0a0f1a')
fig.suptitle('Real Dataset — Sample Images with Ground Truth Bounding Boxes',
             color='white', fontsize=13, fontweight='bold')

indices = random.sample(range(len(pairs)), 8)
colors  = ['#00ff9f', '#ff6b6b', '#ffd600', '#6bb3ff']

for ax, idx in zip(axes.flat, indices):
    img = cv2.cvtColor(cv2.imread(pairs[idx]['img']), cv2.COLOR_BGR2RGB)
    ann = annotations[idx]
    H_img, W_img = img.shape[:2]

    ax.imshow(img)
    for i, (xmin, ymin, xmax, ymax) in enumerate(ann['boxes']):
        c = colors[i % len(colors)]
        rect = mpatches.Rectangle(
            (xmin, ymin), xmax - xmin, ymax - ymin,
            linewidth=2, edgecolor=c, facecolor='none'
        )
        ax.add_patch(rect)
        ax.text(xmin, ymin - 5, ann['labels'][i],
                color=c, fontsize=8, fontweight='bold')

    ax.set_title(f'Img {idx} | {len(ann["boxes"])} obj | {W_img}×{H_img}',
                 color='white', fontsize=9)
    ax.axis('off')
    ax.set_facecolor('#0a0f1a')

plt.tight_layout()
plt.show()

# ─── Distribution plots ───────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
fig.patch.set_facecolor('#0a0f1a')

plot_data = [
    (obj_counts,  'Objects per Image',         '#00ff9f', range(1, max(obj_counts)+2)),
    (box_areas,   'Normalised Box Area',        '#6bb3ff', 20),
    (box_aspects, 'Box Aspect Ratio (w/h)',     '#ff9f00', 20),
]

for ax, (data, title, color, bins) in zip(axes, plot_data):
    ax.set_facecolor('#111827')
    ax.tick_params(colors='white')
    for s in ax.spines.values(): s.set_edgecolor('#334155')
    ax.hist(data, bins=bins, color=color, edgecolor='white', linewidth=0.5, alpha=0.9)
    ax.axvline(np.mean(data), color='white', linestyle='--',
               linewidth=1.5, label=f'Mean={np.mean(data):.2f}')
    ax.set_title(title, color='white', fontweight='bold', fontsize=11)
    ax.legend(facecolor='#1e293b', edgecolor='#334155', labelcolor='white', fontsize=9)
    ax.grid(alpha=0.15, color='white')

fig.suptitle('Dataset Distribution Analysis', color='white',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""## Step 4: Event Camera Simulation (v2e)

We simulate a DVS (Dynamic Vision Sensor) by warping each real image with subtle
synthetic motion — mimicking how a glass object would appear to an event camera
when slightly displaced.

**Why simulate motion from a static image?**
Real event cameras only fire on *change*. Since our dataset has individual frames
(not video), we synthesise motion via:
1. Apply small random affine warp to the image → creates a 'before' and 'after'
2. Run v2e on the resulting frame sequence
3. Glass edges + refraction boundaries generate the strongest events
"""

# ─── Motion-augmented frame generator from a static real image ───────────
def generate_motion_frames(img_bgr: np.ndarray, n_frames: int = 20,
                            max_shift: int = 8, max_rot: float = 2.0) -> List[np.ndarray]:
    """
    Synthesise n_frames by applying a smooth random affine trajectory
    to the input BGR image, simulating camera or object motion.
    """
    H, W = img_bgr.shape[:2]
    cx, cy = W / 2, H / 2

    dx = np.linspace(0, random.uniform(-max_shift, max_shift), n_frames)
    dy = np.linspace(0, random.uniform(-max_shift, max_shift), n_frames)
    da = np.linspace(0, random.uniform(-max_rot,   max_rot),   n_frames)
    ds = np.linspace(1.0, random.uniform(0.97, 1.03),          n_frames)

    frames = []
    for i in range(n_frames):
        M  = cv2.getRotationMatrix2D((cx, cy), da[i], ds[i])
        M[0, 2] += dx[i]
        M[1, 2] += dy[i]
        warped = cv2.warpAffine(img_bgr, M, (W, H),
                                flags=cv2.INTER_LINEAR,
                                borderMode=cv2.BORDER_REFLECT)
        frames.append(warped)
    return frames


# ─── V2E Simulator (fully vectorized) ────────────────────────────────────
class V2ESimulator:
    """
    DVS event simulator — converts a BGR frame sequence to events.
    Uses vectorized numpy (no Python pixel loops).

    Each event: (t, x, y, p) where p=+1 (ON) or p=-1 (OFF)
    Returns dict of numpy arrays for fast downstream processing.
    """
    def __init__(self, threshold_pos=0.15, threshold_neg=0.15,
                 noise_std=0.012, fps=30.0):
        self.C_pos     = threshold_pos
        self.C_neg     = threshold_neg
        self.noise_std = noise_std
        self.dt_us     = 1e6 / fps
        self._ref      = None

    def reset(self):
        self._ref = None

    @staticmethod
    def _to_log(frame_bgr: np.ndarray) -> np.ndarray:
        gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
        return np.log(gray + 1.0)

    def process_sequence(self, frames: List[np.ndarray]) -> Dict:
        """Process a list of BGR frames. Returns dict of arrays."""
        if not frames:
            return {'t': np.array([]), 'x': np.array([]),
                    'y': np.array([]), 'p': np.array([])}

        log_stack = np.stack([self._to_log(f) for f in frames])  # (N,H,W)
        if self.noise_std > 0:
            log_stack += np.random.randn(*log_stack.shape).astype(np.float32) * self.noise_std

        all_t, all_x, all_y, all_p = [], [], [], []
        ref = log_stack[0].copy()

        for i in range(1, len(log_stack)):
            t_us = i * self.dt_us
            diff = log_stack[i] - ref

            for mask, pol in [(diff >= self.C_pos, 1), (diff <= -self.C_neg, -1)]:
                yx = np.argwhere(mask)
                if len(yx):
                    all_t.append(np.full(len(yx), t_us,  dtype=np.float32))
                    all_y.append(yx[:, 0].astype(np.int32))
                    all_x.append(yx[:, 1].astype(np.int32))
                    all_p.append(np.full(len(yx), pol,   dtype=np.int8))

            fired = np.abs(diff) >= self.C_pos
            ref[fired] = log_stack[i][fired]

        if not all_t:
            return {'t': np.array([]), 'x': np.array([]),
                    'y': np.array([]), 'p': np.array([])}

        return {
            't': np.concatenate(all_t),
            'x': np.concatenate(all_x),
            'y': np.concatenate(all_y),
            'p': np.concatenate(all_p),
        }


# ─── Quick demo on one real image ─────────────────────────────────────────
demo_idx    = 0
demo_img    = cv2.imread(pairs[demo_idx]['img'])
demo_ann    = annotations[demo_idx]
demo_frames = generate_motion_frames(demo_img, n_frames=20)

sim_demo = V2ESimulator(threshold_pos=0.15, threshold_neg=0.15,
                        noise_std=0.012, fps=30.0)
demo_events = sim_demo.process_sequence(demo_frames)

n_on  = int(np.sum(demo_events['p'] == 1))
n_off = int(np.sum(demo_events['p'] == -1))
print(f'Event simulation on real image:')
print(f'  Image shape : {demo_img.shape}')
print(f'  ON events   : {n_on:,}')
print(f'  OFF events  : {n_off:,}')
print(f'  Total       : {n_on+n_off:,}')

# ─── Visualise: Real image → Motion frames → Event map ───────────────────
H_d, W_d = demo_img.shape[:2]
ev_img = np.zeros((H_d, W_d, 3), dtype=np.float32)

if demo_events['t'].size > 0:
    x_arr, y_arr, p_arr = demo_events['x'], demo_events['y'], demo_events['p']
    valid = (x_arr >= 0) & (x_arr < W_d) & (y_arr >= 0) & (y_arr < H_d)
    x_arr, y_arr, p_arr = x_arr[valid], y_arr[valid], p_arr[valid]
    on  = p_arr ==  1
    off = p_arr == -1
    np.add.at(ev_img[:, :, 0], (y_arr[on],  x_arr[on]),  0.4)   # R = ON
    np.add.at(ev_img[:, :, 2], (y_arr[off], x_arr[off]), 0.4)   # B = OFF
    ev_img = np.clip(ev_img, 0, 1)

fig, axes = plt.subplots(1, 4, figsize=(18, 5))
fig.patch.set_facecolor('#050a14')
fig.suptitle('Real Image → Motion Simulation → Event Camera Output',
             color='white', fontsize=13, fontweight='bold')

# Original
axes[0].imshow(cv2.cvtColor(demo_img, cv2.COLOR_BGR2RGB))
for xmin, ymin, xmax, ymax in demo_ann['boxes']:
    rect = mpatches.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin,
                               lw=2, edgecolor='#00ff9f', facecolor='none')
    axes[0].add_patch(rect)
axes[0].set_title('Original Image + GT Box', color='white', fontsize=10)

# Frame 5
axes[1].imshow(cv2.cvtColor(demo_frames[5],  cv2.COLOR_BGR2RGB))
axes[1].set_title('Warped Frame 5 (motion sim)', color='white', fontsize=10)

# Frame 15
axes[2].imshow(cv2.cvtColor(demo_frames[15], cv2.COLOR_BGR2RGB))
axes[2].set_title('Warped Frame 15', color='white', fontsize=10)

# Event map
axes[3].imshow(ev_img)
axes[3].set_title(f'Event Map\n🔴 ON:{n_on:,}  🔵 OFF:{n_off:,}',
                  color='white', fontsize=10)

for ax in axes:
    ax.axis('off')
    ax.set_facecolor('#050a14')

plt.tight_layout()
plt.show()

print('Key insight: Glass edges generate the strongest events (highest event density)')
print('These are exactly the features the SNN will learn to detect for grasping!')

"""## Step 5: Voxel Grid — Events → Fixed Tensor (10, H, W)

Raw events are variable-length; neural networks need fixed-size tensors.
We bin events into **T=5 time slices × 2 polarities = 10 channels**.
"""

# ─── Voxel Grid Encoder (vectorized) ─────────────────────────────────────
def events_to_tensor(events: Dict, H: int, W: int, num_bins: int = 5) -> torch.Tensor:
    """
    Convert event dict to voxel tensor of shape (2*num_bins, H, W).
    Channels 0..num_bins-1   = ON  events per time bin
    Channels num_bins..2*n-1 = OFF events per time bin
    """
    voxel = np.zeros((2 * num_bins, H, W), dtype=np.float32)

    t_arr = events['t']
    if len(t_arr) == 0:
        return torch.zeros((2 * num_bins, H, W), dtype=torch.float32)

    x_arr, y_arr, p_arr = events['x'], events['y'], events['p']

    # Assign each event to a time bin
    t_min, t_max = float(t_arr.min()), float(t_arr.max())
    duration = max(t_max - t_min, 1e-6)
    bin_idx  = np.clip(
        np.floor((t_arr - t_min) / duration * num_bins).astype(np.int32),
        0, num_bins - 1
    )

    # Bounds check
    valid    = (x_arr >= 0) & (x_arr < W) & (y_arr >= 0) & (y_arr < H)
    on_mask  = (p_arr ==  1) & valid
    off_mask = (p_arr == -1) & valid

    np.add.at(voxel, (bin_idx[on_mask],            y_arr[on_mask],  x_arr[on_mask]),  1.0)
    np.add.at(voxel, (num_bins + bin_idx[off_mask], y_arr[off_mask], x_arr[off_mask]), 1.0)

    # Per-channel normalisation
    mx = voxel.max(axis=(1, 2), keepdims=True)
    voxel /= np.where(mx > 0, mx, 1.0)

    return torch.from_numpy(voxel)


# ─── Test on demo image ───────────────────────────────────────────────────
H_tgt, W_tgt = 128, 128   # resize target for the SNN input

demo_resized = cv2.resize(demo_img, (W_tgt, H_tgt))
demo_frames_r = generate_motion_frames(demo_resized, n_frames=20)
sim_demo.reset()
demo_events_r = sim_demo.process_sequence(demo_frames_r)
demo_voxel    = events_to_tensor(demo_events_r, H_tgt, W_tgt, num_bins=5)

print(f'Voxel tensor shape : {tuple(demo_voxel.shape)}')
print(f'Value range        : [{demo_voxel.min():.3f}, {demo_voxel.max():.3f}]')
print(f'Non-zero channels  : {(demo_voxel.sum(dim=[1,2]) > 0).sum().item()} / 10')

# ─── Visualise all 10 voxel channels ─────────────────────────────────────
fig, axes = plt.subplots(2, 5, figsize=(18, 8))
fig.patch.set_facecolor('#050a14')
fig.suptitle('Voxel Grid — 10 Channels (5 ON bins + 5 OFF bins) from Real Glass Image',
             color='white', fontsize=13, fontweight='bold')

for i in range(10):
    row = 0 if i < 5 else 1
    col = i if i < 5 else i - 5
    ax  = axes[row][col]
    data = demo_voxel[i].numpy()
    cmap = 'hot' if i < 5 else 'cool'
    im = ax.imshow(data, cmap=cmap, vmin=0, vmax=1, interpolation='nearest')
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    pol = 'ON' if i < 5 else 'OFF'
    bn  = i if i < 5 else i - 5
    ax.set_title(f'Ch{i}: {pol} Bin {bn}  |  {(data>0).sum()} active px',
                 color='white', fontsize=9)
    ax.axis('off')

axes[0][0].set_ylabel('ON channels (0-4)',  color='#ff6b6b', fontsize=11, labelpad=6)
axes[1][0].set_ylabel('OFF channels (5-9)', color='#6bb3ff', fontsize=11, labelpad=6)
plt.tight_layout()
plt.show()

print('Channels with more active pixels = more motion / edge activity at that time bin')
print('Glass refraction edges create the densest event clusters — key for detection!')

"""## Step 6: SNN Architecture — LIF Neurons + Temporal Attention

### Architecture Flow
```
Voxel (10, 128, 128)
  ↓
SpikingEncoder — 5 time bins × shared LIF layers
  Stage1: Conv(2→32) + BN + LIF + MaxPool  → (32, 64, 64)
  Stage2: Conv(32→64) + BN + LIF + MaxPool → (64, 32, 32)
  Stage3: Conv(64→128) + BN + LIF          → (128, 32, 32)
  Stack bins → (5, 128, 32, 32)
  ↓
TemporalAttention — squeeze-excite over time → reweighted bins
  ↓
Temporal mean → (128, 32, 32)
  ↓
DetectionHead — GAP + FC → 4 outputs
  bbox(4) | conf(1) | class(1) | grasp(5)
```
"""

# ─── Surrogate Gradient ───────────────────────────────────────────────────
class SurrogateSpike(torch.autograd.Function):
    """Heaviside forward, fast-sigmoid surrogate backward."""
    @staticmethod
    def forward(ctx, x):
        ctx.save_for_backward(x)
        return (x >= 0).float()

    @staticmethod
    def backward(ctx, grad_output):
        (x,) = ctx.saved_tensors
        grad = 1.0 / (1.0 + torch.abs(x)) ** 2
        return grad_output * grad

surrogate_spike = SurrogateSpike.apply


# ─── LIF Neuron ───────────────────────────────────────────────────────────
class LIFNeuron(nn.Module):
    """
    Leaky Integrate-and-Fire neuron with hard reset.
    v(t) = v(t-1)*(1-1/τ) + x(t)
    spike = 1 if v >= threshold; reset v → 0 after spike
    """
    def __init__(self, tau: float = 2.0, v_thresh: float = 1.0):
        super().__init__()
        self.tau      = tau
        self.v_thresh = v_thresh

    def forward(self, x, v_prev=None):
        if v_prev is None:
            v_prev = torch.zeros_like(x)
        v      = v_prev * (1 - 1 / self.tau) + x
        spikes = surrogate_spike(v - self.v_thresh)
        v_new  = v * (1 - spikes)          # hard reset
        return spikes, v_new


# ─── Spiking Convolutional Block ──────────────────────────────────────────
class SpikingConvBlock(nn.Module):
    """Conv2d → BatchNorm → LIF → (optional MaxPool)"""
    def __init__(self, in_ch: int, out_ch: int, kernel: int = 3,
                 pool: bool = False, tau: float = 2.0):
        super().__init__()
        self.conv     = nn.Conv2d(in_ch, out_ch, kernel, padding=kernel//2, bias=False)
        self.bn       = nn.BatchNorm2d(out_ch)
        self.lif      = LIFNeuron(tau=tau)
        self.pool     = nn.MaxPool2d(2, 2) if pool else nn.Identity()
        self.has_pool = pool

    def forward(self, x, v_prev=None):
        out = self.bn(self.conv(x))
        spikes, v_new = self.lif(out, v_prev)   # v_new at PRE-pool resolution
        return self.pool(spikes), v_new


# ─── Spiking Encoder ──────────────────────────────────────────────────────
class SpikingEncoder(nn.Module):
    """
    Processes T time-bin pairs (ON + OFF) through shared LIF conv layers.
    Membrane state v is carried forward across bins — TRUE temporal memory.
    """
    def __init__(self, in_bins: int = 10, base_ch: int = 32):
        super().__init__()
        self.T          = in_bins // 2
        self.stage1     = SpikingConvBlock(2, base_ch,       pool=True)
        self.stage2     = SpikingConvBlock(base_ch, base_ch*2, pool=True)
        self.stage3     = SpikingConvBlock(base_ch*2, base_ch*4, pool=False)
        self.out_ch     = base_ch * 4

    def forward(self, voxel):
        T = voxel.shape[1] // 2
        v1 = v2 = v3 = None
        outputs = []
        for t in range(T):
            x_t = voxel[:, [t, t + T], :, :]
            s1, v1 = self.stage1(x_t, v1)
            s2, v2 = self.stage2(s1,  v2)
            s3, v3 = self.stage3(s2,  v3)
            outputs.append(s3)
        return torch.stack(outputs, dim=1)   # (B, T, C, H', W')


# ─── Temporal Attention ───────────────────────────────────────────────────
class TemporalAttention(nn.Module):
    """
    Squeeze-and-Excitation over TIME.
    Learns which event-time bins are most informative for detecting glass.
    """
    def __init__(self, n_bins: int, channels: int, ratio: int = 4):
        super().__init__()
        bottleneck = max(n_bins // ratio, 2)
        self.fc1   = nn.Linear(n_bins, bottleneck, bias=False)
        self.fc2   = nn.Linear(bottleneck, n_bins,  bias=False)
        self.bn    = nn.BatchNorm1d(bottleneck)

    def forward(self, x):
        B, T, C, H, W = x.shape
        energy = x.mean(dim=[2, 3, 4])               # (B, T)
        e = F.relu(self.bn(self.fc1(energy)))
        e = torch.sigmoid(self.fc2(e))               # (B, T)
        return x * e.view(B, T, 1, 1, 1)


# ─── Detection + Grasp Head ───────────────────────────────────────────────
class DetectionHead(nn.Module):
    """
    4 parallel output heads after global average pooling:
    - bbox  (4): [cx, cy, w, h] normalised
    - conf  (1): objectness logit
    - cls   (1): class logit (transparent vs opaque, binary)
    - grasp (5): [cx, cy, z, angle, width] for robot control
    """
    def __init__(self, in_channels: int = 128):
        super().__init__()
        self.gap = nn.AdaptiveAvgPool2d(1)
        self.shared = nn.Sequential(
            nn.Linear(in_channels, 256), nn.ReLU(inplace=True),
            nn.Dropout(0.3),
            nn.Linear(256, 128),         nn.ReLU(inplace=True),
        )
        self.bbox_head  = nn.Linear(128, 4)
        self.conf_head  = nn.Linear(128, 1)
        self.cls_head   = nn.Linear(128, 1)   # binary: transparent
        self.grasp_head = nn.Linear(128, 5)

    def forward(self, feat):
        x    = self.gap(feat).flatten(1)
        x    = self.shared(x)
        bbox  = torch.sigmoid(self.bbox_head(x))
        conf  = self.conf_head(x)
        cls   = self.cls_head(x)
        grasp = self.grasp_head(x)
        return {'bbox': bbox, 'conf': conf, 'cls': cls, 'grasp': grasp}


# ─── Full NeurOGrasp SNN ──────────────────────────────────────────────────
class NeurOGraspSNN(nn.Module):
    """Complete pipeline: SpikingEncoder → TemporalAttention → DetectionHead"""
    def __init__(self, n_bins: int = 5, base_ch: int = 32):
        super().__init__()
        self.encoder  = SpikingEncoder(n_bins * 2, base_ch)
        self.attn     = TemporalAttention(n_bins, self.encoder.out_ch)
        self.head     = DetectionHead(self.encoder.out_ch)

    def forward(self, voxel):
        enc      = self.encoder(voxel)        # (B, T, C, H', W')
        attended = self.attn(enc)             # (B, T, C, H', W') — reweighted
        feat     = attended.mean(dim=1)       # (B, C, H', W')
        return self.head(feat)


# ─── Build model ──────────────────────────────────────────────────────────
model = NeurOGraspSNN(n_bins=5, base_ch=32).to(device)
total_p = sum(p.numel() for p in model.parameters())

print('=' * 55)
print('  NeurOGraspSNN — Architecture Summary')
print('=' * 55)
print(f'  Parameters : {total_p:,}')
print(f'  Model size : {total_p*4/1e6:.2f} MB')
print()

# Forward pass test
dummy = torch.rand(2, 10, H_tgt, W_tgt).to(device)
with torch.no_grad():
    out = model(dummy)
print('  Forward pass test (batch=2):')
print(f'  Input  : {tuple(dummy.shape)}')
for k, v in out.items():
    print(f'  {k:5s}  : {tuple(v.shape)}')
print()
print('  Per-module params:')
for name, mod in model.named_children():
    p = sum(x.numel() for x in mod.parameters())
    print(f'    {name:<20} : {p:>7,}')
print('=' * 55)

"""## Step 7: Loss Functions"""

# ─── Combined NeurOGrasp Loss ─────────────────────────────────────────────
class NeurOGraspLoss(nn.Module):
    """
    Weighted combination of 4 task losses:
    - BBox  : SmoothL1 (robust regression, bounded gradients)
    - Conf  : BCEWithLogits (raw logits, numerically stable)
    - Class : BCEWithLogits (binary: transparent or not)
    - Grasp : SmoothL1 (robot pose regression)

    Weights: bbox=2.0, conf=1.0, cls=0.5, grasp=1.5
    """
    def __init__(self):
        super().__init__()
        self.smooth_l1 = nn.SmoothL1Loss()
        self.bce       = nn.BCEWithLogitsLoss()

    def forward(self, preds: Dict, targets: Dict) -> Dict:
        l_bbox  = 2.0 * self.smooth_l1(preds['bbox'],  targets['bbox'])
        l_conf  = 1.0 * self.bce(       preds['conf'],  targets['conf'])
        l_cls   = 0.5 * self.bce(       preds['cls'],   targets['cls'])
        l_grasp = 1.5 * self.smooth_l1(preds['grasp'], targets['grasp'])
        total   = l_bbox + l_conf + l_cls + l_grasp
        return {'total': total, 'bbox': l_bbox, 'conf': l_conf,
                'cls': l_cls, 'grasp': l_grasp}


criterion = NeurOGraspLoss()
print('✅ NeurOGraspLoss ready')
print('  bbox  weight : 2.0  (SmoothL1 — spatial accuracy priority)')
print('  conf  weight : 1.0  (BCEWithLogits — objectness)')
print('  cls   weight : 0.5  (BCEWithLogits — transparent class)')
print('  grasp weight : 1.5  (SmoothL1 — robot grasp pose)')

"""## Step 8: PyTorch Dataset + Training Pipeline

### RealGlassEventDataset
- Loads real JPG images and Pascal VOC annotations
- For each sample: apply motion warp → simulate events → encode voxel
- Labels derived from ground truth bounding boxes
- Multiple objects per image → use the largest box as the primary target
- Data augmentation: flips, brightness, temporal dropout
"""

# ─── PyTorch Dataset ──────────────────────────────────────────────────────
class RealGlassEventDataset(Dataset):
    """
    Real transparent glass dataset with v2e event simulation.

    Each __getitem__:
    1. Load real JPG image
    2. Resize to (H_tgt, W_tgt)
    3. Synthesise motion → 20 warped frames
    4. Simulate events (V2ESimulator)
    5. Encode voxel (10, H, W)
    6. Build targets from GT bbox
    """
    def __init__(self, pairs: List[Dict], annotations: List[Dict],
                 H: int = 128, W: int = 128,
                 n_frames: int = 20, num_bins: int = 5,
                 augment: bool = True):
        self.pairs       = pairs
        self.annotations = annotations
        self.H, self.W   = H, W
        self.n_frames    = n_frames
        self.num_bins    = num_bins
        self._make_sim()
        self.augment     = augment

    def _make_sim(self):
        self.sim = V2ESimulator(threshold_pos=0.15, threshold_neg=0.15,
                                noise_std=0.012, fps=30.0)

    def __len__(self):
        return len(self.pairs)

    def _pick_primary_box(self, ann: Dict):
        """Return the largest bounding box (primary grasp target)."""
        best_box, best_area = ann['boxes'][0], 0
        for box in ann['boxes']:
            area = (box[2] - box[0]) * (box[3] - box[1])
            if area > best_area:
                best_box, best_area = box, area
        return best_box

    def __getitem__(self, idx):
        img_bgr = cv2.imread(self.pairs[idx]['img'])
        ann     = self.annotations[idx]
        orig_H, orig_W = img_bgr.shape[:2]

        # Resize
        img_bgr = cv2.resize(img_bgr, (self.W, self.H))

        # Motion frames → events → voxel
        frames  = generate_motion_frames(img_bgr, n_frames=self.n_frames)
        self.sim.reset()
        events  = self.sim.process_sequence(frames)
        voxel   = events_to_tensor(events, self.H, self.W, self.num_bins)

        # Ground truth from largest box
        xmin, ymin, xmax, ymax = self._pick_primary_box(ann)
        cx  = ((xmin + xmax) / 2) / orig_W
        cy  = ((ymin + ymax) / 2) / orig_H
        bw  = (xmax - xmin) / orig_W
        bh  = (ymax - ymin) / orig_H
        cx  = float(np.clip(cx, 0, 1))
        cy  = float(np.clip(cy, 0, 1))
        bw  = float(np.clip(bw, 0.01, 1))
        bh  = float(np.clip(bh, 0.01, 1))

        # Augmentation
        if self.augment:
            # Horizontal flip
            if random.random() < 0.5:
                voxel = torch.flip(voxel, dims=[-1])
                cx    = 1.0 - cx
            # Vertical flip
            if random.random() < 0.3:
                voxel = torch.flip(voxel, dims=[-2])
                cy    = 1.0 - cy
            # Gaussian noise
            if random.random() < 0.5:
                voxel = (voxel + torch.randn_like(voxel) * random.uniform(0.01, 0.05)).clamp_(0, 1)
            # Temporal bin dropout
            if random.random() < 0.4:
                b = random.randint(0, self.num_bins - 1)
                voxel[b] = 0; voxel[b + self.num_bins] = 0
            # Brightness scale
            if random.random() < 0.4:
                voxel = (voxel * random.uniform(0.7, 1.3)).clamp_(0, 1)

        # Grasp target: cx, cy, z (0.5 default), angle (0.5 = 0°), width=bw
        targets = {
            'bbox' : torch.tensor([cx, cy, bw, bh], dtype=torch.float32),
            'conf' : torch.tensor([1.0], dtype=torch.float32),
            'cls'  : torch.tensor([1.0], dtype=torch.float32),  # transparent
            'grasp': torch.tensor([cx, cy, 0.5, 0.5, bw], dtype=torch.float32),
        }
        return voxel, targets


# ─── Train / Val / Test split (70/15/15) ─────────────────────────────────
random.seed(42)
all_idx = list(range(len(pairs)))
random.shuffle(all_idx)

n       = len(all_idx)
n_train = int(0.70 * n)
n_val   = int(0.15 * n)

train_idx = all_idx[:n_train]
val_idx   = all_idx[n_train : n_train + n_val]
test_idx  = all_idx[n_train + n_val :]

pairs_train = [pairs[i] for i in train_idx]
pairs_val   = [pairs[i] for i in val_idx]
pairs_test  = [pairs[i] for i in test_idx]

ann_train   = [annotations[i] for i in train_idx]
ann_val     = [annotations[i] for i in val_idx]
ann_test    = [annotations[i] for i in test_idx]

print(f'Split: {len(train_idx)} train | {len(val_idx)} val | {len(test_idx)} test')

# Datasets
train_ds = RealGlassEventDataset(pairs_train, ann_train, H=H_tgt, W=W_tgt, augment=True)
val_ds   = RealGlassEventDataset(pairs_val,   ann_val,   H=H_tgt, W=W_tgt, augment=False)
test_ds  = RealGlassEventDataset(pairs_test,  ann_test,  H=H_tgt, W=W_tgt, augment=False)

# DataLoaders — num_workers=0 avoids simulator pickling issues
train_loader = DataLoader(train_ds, batch_size=8,  shuffle=True,  num_workers=0)
val_loader   = DataLoader(val_ds,   batch_size=8,  shuffle=False, num_workers=0)
test_loader  = DataLoader(test_ds,  batch_size=4,  shuffle=False, num_workers=0)

print(f'Train batches : {len(train_loader)}')
print(f'Val   batches : {len(val_loader)}')

# Verify a sample
v, t = train_ds[0]
print(f'\nSample voxel shape : {tuple(v.shape)}')
print(f'Bbox target        : {t["bbox"].numpy()}')
print(f'Grasp target       : {t["grasp"].numpy()}')

# ─── Training Utilities ───────────────────────────────────────────────────
class AverageMeter:
    def __init__(self): self.reset()
    def reset(self): self.avg = self.sum = self.count = 0.0
    def update(self, val, n=1):
        self.sum += val * n; self.count += n
        self.avg = self.sum / max(self.count, 1)

def cosine_lr(epoch, warmup=3, total=50):
    if epoch < warmup:
        return (epoch + 1) / warmup
    progress = (epoch - warmup) / max(total - warmup, 1)
    return 0.5 * (1 + np.cos(np.pi * progress))


# ─── Training Loop ────────────────────────────────────────────────────────
EPOCHS       = 50
LR           = 1e-3
WEIGHT_DECAY = 3e-4
PATIENCE     = 10

model     = NeurOGraspSNN(n_bins=5, base_ch=32).to(device)
criterion = NeurOGraspLoss()
optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = optim.lr_scheduler.LambdaLR(
    optimizer, lambda e: cosine_lr(e, warmup=3, total=EPOCHS)
)

use_amp   = device.type == 'cuda'
scaler    = torch.cuda.amp.GradScaler() if use_amp else None

history = defaultdict(list)
best_val, best_wts = float('inf'), None
patience_counter   = 0

print(f'Training NeurOGraspSNN on {device}')
print(f'Epochs={EPOCHS}  LR={LR}  Patience={PATIENCE}  AMP={use_amp}')
print(f'Model params: {sum(p.numel() for p in model.parameters()):,}')
print()

for epoch in range(EPOCHS):
    t0 = time.time()

    # ── Train ────────────────────────────────────────────────────────────
    model.train()
    meters = {k: AverageMeter() for k in ['total','bbox','conf','cls','grasp']}

    for voxel, targets in tqdm(train_loader, desc=f'Ep {epoch+1:>2}/{EPOCHS}',
                               leave=False, ncols=80):
        voxel = voxel.to(device)
        tgts  = {k: v.to(device) for k, v in targets.items()}

        optimizer.zero_grad(set_to_none=True)

        if use_amp:
            with torch.amp.autocast('cuda'):
                preds  = model(voxel)
                losses = criterion(preds, tgts)
            scaler.scale(losses['total']).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
        else:
            preds  = model(voxel)
            losses = criterion(preds, tgts)
            losses['total'].backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

        B = voxel.size(0)
        for k in meters:
            meters[k].update(losses[k].item(), B)

    # ── Validate ─────────────────────────────────────────────────────────
    model.eval()
    val_m    = {k: AverageMeter() for k in ['total', 'bbox', 'grasp']}
    val_conf = 0.0

    with torch.no_grad():
        for voxel, targets in val_loader:
            voxel = voxel.to(device)
            tgts  = {k: v.to(device) for k, v in targets.items()}
            preds = model(voxel)
            loss  = criterion(preds, tgts)
            B = voxel.size(0)
            for k in val_m: val_m[k].update(loss[k].item(), B)
            val_conf += torch.sigmoid(preds['conf']).mean().item()

    scheduler.step()

    tr_loss  = meters['total'].avg
    vl_loss  = val_m['total'].avg
    vl_conf  = val_conf / max(len(val_loader), 1)
    cur_lr   = optimizer.param_groups[0]['lr']
    elapsed  = time.time() - t0

    for k in history:
        pass
    history['train_loss'].append(tr_loss)
    history['val_loss'].append(vl_loss)
    history['val_conf'].append(vl_conf)
    history['lr'].append(cur_lr)
    history['bbox_loss'].append(meters['bbox'].avg)
    history['grasp_loss'].append(meters['grasp'].avg)

    is_best = vl_loss < best_val
    if is_best:
        best_val = vl_loss
        best_wts = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        patience_counter = 0
    else:
        patience_counter += 1

    star = ' ★' if is_best else ''
    print(f'Ep {epoch+1:>2}/{EPOCHS} | '
          f'tr={tr_loss:.4f} | vl={vl_loss:.4f} | '
          f'bbox={meters["bbox"].avg:.4f} | '
          f'conf={vl_conf:.3f} | lr={cur_lr:.2e} | '
          f'{elapsed:.0f}s{star}')

    if patience_counter >= PATIENCE:
        print(f'\nEarly stopping at epoch {epoch+1} (patience={PATIENCE})')
        break

model.load_state_dict(best_wts)
print(f'\n✅ Training complete! Best val loss: {best_val:.4f}')

"""## Step 9: Training Curves & Analysis"""

epochs_ran = list(range(1, len(history['train_loss']) + 1))

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.patch.set_facecolor('#0a0f1a')
fig.suptitle('NeurOGrasp Training on Real Transparent Glass Dataset',
             color='white', fontsize=14, fontweight='bold')

plots = [
    (axes[0,0], 'Total Loss',            'train_loss', 'val_loss',   '#ff6b6b', '#00ff9f'),
    (axes[0,1], 'BBox Regression Loss',  'bbox_loss',  None,         '#ffd600', None),
    (axes[1,0], 'Grasp Regression Loss', 'grasp_loss', None,         '#b66dff', None),
    (axes[1,1], 'Validation Confidence', None,         'val_conf',   None,      '#6bb3ff'),
]

for ax, title, train_k, val_k, tc, vc in plots:
    ax.set_facecolor('#111827')
    ax.tick_params(colors='white')
    for s in ax.spines.values(): s.set_edgecolor('#334155')
    ax.grid(alpha=0.15, color='white')
    if train_k and train_k in history:
        ax.plot(epochs_ran, history[train_k], color=tc, lw=2.5, marker='o',
                markersize=4, label='Train')
    if val_k and val_k in history:
        ax.plot(epochs_ran, history[val_k], color=vc, lw=2.5, marker='s',
                markersize=4, label='Val')
    ax.set_title(title, color='white', fontweight='bold', fontsize=12)
    ax.set_xlabel('Epoch', color='white')
    ax.legend(facecolor='#1e293b', edgecolor='#334155', labelcolor='white')

plt.tight_layout()
plt.show()

print('Training Summary:')
print(f'  Epochs run       : {len(epochs_ran)}')
print(f'  Initial val loss : {history["val_loss"][0]:.4f}')
print(f'  Best val loss    : {best_val:.4f}')
impr = (1 - best_val / history['val_loss'][0]) * 100
print(f'  Improvement      : {impr:.1f}%')
print(f'  Final confidence : {history["val_conf"][-1]:.3f}')

"""## Step 10: Inference on Real Test Images"""

# ─── Inference pipeline ───────────────────────────────────────────────────
def infer_single(img_bgr: np.ndarray, model: nn.Module,
                 H: int = 128, W: int = 128,
                 conf_thresh: float = 0.4) -> Dict:
    """Run full NeurOGrasp pipeline on one BGR image."""
    model.eval()
    img_r  = cv2.resize(img_bgr, (W, H))
    frames = generate_motion_frames(img_r, n_frames=20)
    sim    = V2ESimulator(threshold_pos=0.15, threshold_neg=0.15,
                          noise_std=0.012, fps=30.0)
    events = sim.process_sequence(frames)
    voxel  = events_to_tensor(events, H, W, num_bins=5).unsqueeze(0).to(device)

    with torch.no_grad():
        preds = model(voxel)

    bbox  = preds['bbox'][0].cpu().numpy()
    conf  = float(torch.sigmoid(preds['conf'][0]).item())
    cls   = float(torch.sigmoid(preds['cls'][0]).item())
    grasp = preds['grasp'][0].cpu().numpy()

    return {
        'bbox':    bbox,
        'conf':    conf,
        'cls':     cls,
        'grasp':   grasp,
        'attempt': conf >= conf_thresh,
        'voxel':   voxel.squeeze(0).cpu(),
        'events':  events,
    }


# ─── Run inference on all test images ─────────────────────────────────────
print(f'Running inference on {len(pairs_test)} test images...')
test_results = []

for i, (pair, ann) in enumerate(zip(pairs_test, ann_test)):
    img = cv2.imread(pair['img'])
    res = infer_single(img, model, H=H_tgt, W=W_tgt, conf_thresh=0.4)
    res['img_path'] = pair['img']
    res['ann']      = ann
    res['img_bgr']  = img
    test_results.append(res)

n_attempts = sum(r['attempt'] for r in test_results)
avg_conf   = np.mean([r['conf'] for r in test_results])

print(f'\nTest Results:')
print(f'  Images evaluated  : {len(test_results)}')
print(f'  Grasp attempts    : {n_attempts}/{len(test_results)} ({n_attempts/len(test_results)*100:.0f}%)')
print(f'  Avg confidence    : {avg_conf:.3f}')
print(f'  Avg cls score     : {np.mean([r["cls"] for r in test_results]):.3f}')

"""## Step 11: Grasp Visualisation on Real Images"""

# ─── Visualise predictions on test images ────────────────────────────────
n_show = min(8, len(test_results))
fig, axes = plt.subplots(2, 4, figsize=(18, 10))
fig.patch.set_facecolor('#050a14')
fig.suptitle('NeurOGrasp Inference — Real Transparent Glass Test Images',
             color='white', fontsize=13, fontweight='bold')

for ax, res in zip(axes.flat, test_results[:n_show]):
    img_vis = cv2.cvtColor(res['img_bgr'].copy(), cv2.COLOR_BGR2RGB)
    H_img, W_img = img_vis.shape[:2]

    bbox  = res['bbox']
    grasp = res['grasp']
    conf  = res['conf']

    # Ground truth boxes (green)
    for xmin, ymin, xmax, ymax in res['ann']['boxes']:
        rect = mpatches.Rectangle(
            (xmin, ymin), xmax - xmin, ymax - ymin,
            lw=2, edgecolor='#00ff9f', facecolor='none', linestyle='--'
        )
        ax.add_patch(rect)

    # Predicted bbox (yellow)
    bx = int(bbox[0] * W_img); by = int(bbox[1] * H_img)
    bw = int(bbox[2] * W_img); bh = int(bbox[3] * H_img)
    rect_pred = mpatches.Rectangle(
        (max(0, bx - bw//2), max(0, by - bh//2)), bw, bh,
        lw=2, edgecolor='#ffd600', facecolor='none'
    )
    ax.add_patch(rect_pred)

    # Grasp point (orange circle)
    gx = int(grasp[0] * W_img); gy = int(grasp[1] * H_img)
    circle = plt.Circle((gx, gy), radius=12, color='#ff6b00', fill=True, alpha=0.8)
    ax.add_patch(circle)
    circle2 = plt.Circle((gx, gy), radius=16, color='#ffaa00', fill=False, lw=2)
    ax.add_patch(circle2)

    # Grasp angle line
    angle_rad = (grasp[3] - 0.5) * np.pi
    arm_len   = int(grasp[4] * W_img * 0.4)
    dx = int(arm_len * np.cos(angle_rad))
    dy = int(arm_len * np.sin(angle_rad))
    ax.annotate('', xy=(gx + dx, gy + dy), xytext=(gx - dx, gy - dy),
                arrowprops=dict(arrowstyle='<->', color='#ff6b00', lw=2))

    ax.imshow(img_vis)
    status = '✅ GRASP' if res['attempt'] else '⚠️ SKIP'
    ax.set_title(f'{status}  conf={conf:.2f}  cls={res["cls"]:.2f}',
                 color='#00ff9f' if res['attempt'] else '#ff6b6b', fontsize=9)
    ax.axis('off')

# Legend
legend_elements = [
    mpatches.Patch(edgecolor='#00ff9f', facecolor='none', lw=2, label='GT Box (dashed)', ls='--'),
    mpatches.Patch(edgecolor='#ffd600', facecolor='none', lw=2, label='Pred Box'),
    mpatches.Patch(facecolor='#ff6b00', label='Grasp Point'),
]
fig.legend(handles=legend_elements, loc='lower center', ncol=3,
           facecolor='#1e293b', edgecolor='#334155', labelcolor='white', fontsize=10)
plt.tight_layout(rect=[0, 0.05, 1, 1])
plt.show()

# ─── Detailed view: best & worst predictions ──────────────────────────────
sorted_by_conf = sorted(test_results, key=lambda r: r['conf'], reverse=True)
best  = sorted_by_conf[0]
worst = sorted_by_conf[-1]

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.patch.set_facecolor('#050a14')
fig.suptitle('Detailed View: Best vs Worst Prediction + Event Maps',
             color='white', fontsize=13, fontweight='bold')

for row, (res, label) in enumerate([(best, 'BEST'), (worst, 'WORST')]):
    img_rgb = cv2.cvtColor(res['img_bgr'], cv2.COLOR_BGR2RGB)
    H_i, W_i = img_rgb.shape[:2]

    # Col 0: Original with GT
    ax = axes[row][0]
    ax.imshow(img_rgb)
    for xmin, ymin, xmax, ymax in res['ann']['boxes']:
        rect = mpatches.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin,
                                   lw=2, edgecolor='#00ff9f', facecolor='none')
        ax.add_patch(rect)
    ax.set_title(f'{label} — Original + GT Box', color='white', fontsize=10)
    ax.axis('off')

    # Col 1: Prediction overlay
    ax = axes[row][1]
    ax.imshow(img_rgb)
    bbox = res['bbox']
    bx = int(bbox[0]*W_i); by = int(bbox[1]*H_i)
    bw_ = int(bbox[2]*W_i); bh_ = int(bbox[3]*H_i)
    ax.add_patch(mpatches.Rectangle(
        (max(0,bx-bw_//2), max(0,by-bh_//2)), bw_, bh_,
        lw=2, edgecolor='#ffd600', facecolor='none'))
    gx = int(res['grasp'][0]*W_i); gy = int(res['grasp'][1]*H_i)
    ax.plot(gx, gy, 'o', color='#ff6b00', markersize=12, markeredgewidth=2,
            markeredgecolor='#ffaa00')
    ax.set_title(f'Pred | conf={res["conf"]:.3f} | cls={res["cls"]:.3f}',
                 color='white', fontsize=10)
    ax.axis('off')

    # Col 2: Event map
    ax = axes[row][2]
    ev = res['events']
    ev_img = np.zeros((H_tgt, W_tgt, 3), dtype=np.float32)
    if ev['t'].size > 0:
        x_a, y_a, p_a = ev['x'], ev['y'], ev['p']
        valid = (x_a>=0)&(x_a<W_tgt)&(y_a>=0)&(y_a<H_tgt)
        x_a, y_a, p_a = x_a[valid], y_a[valid], p_a[valid]
        np.add.at(ev_img[:,:,0], (y_a[p_a==1], x_a[p_a==1]), 0.4)
        np.add.at(ev_img[:,:,2], (y_a[p_a==-1],x_a[p_a==-1]), 0.4)
        ev_img = np.clip(ev_img, 0, 1)
    ax.imshow(ev_img)
    n_ev = len(ev['t'])
    ax.set_title(f'Event Map | {n_ev:,} events', color='white', fontsize=10)
    ax.axis('off')

for ax in axes.flat:
    ax.set_facecolor('#050a14')

plt.tight_layout()
plt.show()

print(f'Best  prediction: conf={best["conf"]:.3f}  bbox={best["bbox"].round(3)}')
print(f'Worst prediction: conf={worst["conf"]:.3f}  bbox={worst["bbox"].round(3)}')

# ─── Quantitative evaluation: IoU + Grasp metrics ────────────────────────
def compute_iou(pred_box, gt_box, img_W, img_H):
    """pred_box in [cx,cy,w,h] norm. gt_box in [xmin,ymin,xmax,ymax] pixel."""
    px1 = (pred_box[0] - pred_box[2]/2) * img_W
    py1 = (pred_box[1] - pred_box[3]/2) * img_H
    px2 = (pred_box[0] + pred_box[2]/2) * img_W
    py2 = (pred_box[1] + pred_box[3]/2) * img_H

    gx1, gy1, gx2, gy2 = gt_box

    ix1 = max(px1, gx1); iy1 = max(py1, gy1)
    ix2 = min(px2, gx2); iy2 = min(py2, gy2)

    inter = max(0, ix2-ix1) * max(0, iy2-iy1)
    union = ((px2-px1)*(py2-py1) + (gx2-gx1)*(gy2-gy1) - inter)
    return inter / max(union, 1e-6)


ious, conf_scores, cls_scores, grasp_errs = [], [], [], []

for res in test_results:
    ann    = res['ann']
    img    = res['img_bgr']
    H_i, W_i = img.shape[:2]

    # IoU with largest GT box
    gt_box = max(ann['boxes'], key=lambda b: (b[2]-b[0])*(b[3]-b[1]))
    iou    = compute_iou(res['bbox'], gt_box, W_i, H_i)
    ious.append(iou)
    conf_scores.append(res['conf'])
    cls_scores.append(res['cls'])

    # Grasp centre error (normalised)
    gt_cx = ((gt_box[0]+gt_box[2])/2) / W_i
    gt_cy = ((gt_box[1]+gt_box[3])/2) / H_i
    err   = np.sqrt((res['grasp'][0]-gt_cx)**2 + (res['grasp'][1]-gt_cy)**2)
    grasp_errs.append(err)

ap50     = np.mean(np.array(ious) > 0.5)
ap25     = np.mean(np.array(ious) > 0.25)
mean_iou = np.mean(ious)

print('=' * 50)
print('  Test Set Evaluation')
print('=' * 50)
print(f'  mIoU               : {mean_iou:.3f}')
print(f'  AP@IoU>0.25        : {ap25:.3f}  ({ap25*100:.0f}%)')
print(f'  AP@IoU>0.50        : {ap50:.3f}  ({ap50*100:.0f}%)')
print(f'  Avg confidence     : {np.mean(conf_scores):.3f}')
print(f'  Avg cls score      : {np.mean(cls_scores):.3f}')
print(f'  Grasp centre error : {np.mean(grasp_errs):.4f} (norm)')
print(f'                     : {np.mean(grasp_errs)*H_tgt:.1f}px (at {H_tgt}px)')
print(f'  Grasp attempt rate : {n_attempts/len(test_results)*100:.0f}%')
print('=' * 50)

"""## Step 12: Ablation Study — Temporal Attention Contribution"""

# ─── Ablation models ──────────────────────────────────────────────────────
class SNNNoAttention(nn.Module):
    """Baseline: SNN without temporal attention (plain mean)."""
    def __init__(self, n_bins=5, base_ch=24):
        super().__init__()
        self.encoder = SpikingEncoder(n_bins*2, base_ch)
        self.head    = DetectionHead(self.encoder.out_ch)
    def forward(self, v):
        return self.head(self.encoder(v).mean(dim=1))

class SNNSingleBin(nn.Module):
    """Baseline: only first time bin — no temporal information."""
    def __init__(self, n_bins=5, base_ch=24):
        super().__init__()
        self.encoder = SpikingEncoder(n_bins*2, base_ch)
        self.head    = DetectionHead(self.encoder.out_ch)
    def forward(self, v):
        return self.head(self.encoder(v)[:, 0])


def quick_train_ablation(ModelClass, name, n_epochs=8):
    """Train an ablation variant on the real dataset (small epochs)."""
    m    = ModelClass(n_bins=5, base_ch=24).to(device)
    opt  = optim.AdamW(m.parameters(), lr=1e-3, weight_decay=3e-4)
    crit = NeurOGraspLoss()

    val_losses = []
    for ep in range(n_epochs):
        m.train()
        for voxel, targets in train_loader:
            voxel = voxel.to(device)
            tgts  = {k: v.to(device) for k, v in targets.items()}
            opt.zero_grad(set_to_none=True)
            loss = crit(m(voxel), tgts)['total']
            loss.backward()
            torch.nn.utils.clip_grad_norm_(m.parameters(), 1.0)
            opt.step()

        m.eval()
        vl = 0.0
        with torch.no_grad():
            for voxel, targets in val_loader:
                voxel = voxel.to(device)
                tgts  = {k: v.to(device) for k, v in targets.items()}
                vl   += crit(m(voxel), tgts)['total'].item()
        val_losses.append(vl / max(len(val_loader), 1))

    print(f'  {name:<40} final val = {val_losses[-1]:.4f}')
    return val_losses


print('Ablation Study (8 epochs each on real dataset):')
abl_results = {}
abl_results['Full SNN + Temporal Attention'] = [
    history['val_loss'][i] for i in range(min(8, len(history['val_loss'])))
]
abl_results['SNN — No Attention (mean)']     = quick_train_ablation(SNNNoAttention, 'No Attention')
abl_results['SNN — Single Bin (no time)']    = quick_train_ablation(SNNSingleBin,   'Single Bin')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig.patch.set_facecolor('#0a0f1a')

colors_abl = {
    'Full SNN + Temporal Attention': '#00ff9f',
    'SNN — No Attention (mean)':     '#6bb3ff',
    'SNN — Single Bin (no time)':    '#ff6b6b',
}

for ax in [ax1, ax2]:
    ax.set_facecolor('#111827')
    ax.tick_params(colors='white')
    for s in ax.spines.values(): s.set_edgecolor('#334155')
    ax.grid(alpha=0.15, color='white')

for name, losses in abl_results.items():
    ax1.plot(range(1, len(losses)+1), losses,
             color=colors_abl[name], lw=2.5, marker='o', markersize=5, label=name)

ax1.set_title('Ablation: Val Loss per Epoch (Real Dataset)', color='white', fontweight='bold')
ax1.set_xlabel('Epoch', color='white'); ax1.set_ylabel('Val Loss', color='white')
ax1.legend(facecolor='#1e293b', edgecolor='#334155', labelcolor='white', fontsize=9)

names  = list(abl_results.keys())
finals = [v[-1] for v in abl_results.values()]
ax2.barh(range(len(names)), finals, color=[colors_abl[n] for n in names],
         edgecolor='white', linewidth=0.8)
ax2.set_yticks(range(len(names)))
ax2.set_yticklabels([n.replace(' — ', '\n') for n in names], color='white', fontsize=9)
ax2.set_title('Final Val Loss (Lower = Better)', color='white', fontweight='bold')
ax2.set_xlabel('Validation Loss', color='white')
for i, v in enumerate(finals):
    ax2.text(v + 0.003, i, f'{v:.4f}', color='white', va='center', fontsize=10)

fig.suptitle('Ablation Study on Real Transparent Glass Dataset',
             color='white', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

best_abl  = names[np.argmin(finals)]
worst_abl = names[np.argmax(finals)]
gain = (finals[np.argmax(finals)] - finals[np.argmin(finals)]) / finals[np.argmax(finals)] * 100
print(f'Best  variant : {best_abl} ({min(finals):.4f})')
print(f'Worst variant : {worst_abl} ({max(finals):.4f})')
print(f'Temporal Attention gain : {gain:.1f}% improvement over worst baseline')

"""## Step 13: Results Summary & Robot Workspace Mapping"""

# ─── Batch results dashboard ──────────────────────────────────────────────
fig = plt.figure(figsize=(16, 12))
fig.patch.set_facecolor('#0a0f1a')
gs  = GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)
fig.suptitle('NeurOGrasp — Complete Results Dashboard (Real Dataset)',
             color='white', fontsize=14, fontweight='bold')

def style_ax(ax):
    ax.set_facecolor('#111827')
    ax.tick_params(colors='white')
    for s in ax.spines.values(): s.set_edgecolor('#334155')
    ax.grid(alpha=0.15, color='white')

# 1. IoU distribution
ax1 = fig.add_subplot(gs[0, 0])
style_ax(ax1)
ax1.hist(ious, bins=10, color='#00ff9f', edgecolor='white', linewidth=0.5, alpha=0.9)
ax1.axvline(0.5, color='#ffd600', lw=2, linestyle='--', label='IoU=0.5')
ax1.axvline(np.mean(ious), color='white', lw=1.5, linestyle=':', label=f'Mean={np.mean(ious):.2f}')
ax1.set_title('IoU Distribution', color='white', fontweight='bold')
ax1.set_xlabel('IoU Score', color='white')
ax1.legend(facecolor='#1e293b', edgecolor='#334155', labelcolor='white', fontsize=8)

# 2. Confidence scores
ax2 = fig.add_subplot(gs[0, 1])
style_ax(ax2)
colors_c = ['#00ff9f' if c >= 0.4 else '#ff6b6b' for c in conf_scores]
ax2.bar(range(len(conf_scores)), conf_scores, color=colors_c, edgecolor='white', linewidth=0.4)
ax2.axhline(0.4, color='#ffd600', lw=2, linestyle='--', label='Grasp threshold')
ax2.set_title('Confidence per Test Image', color='white', fontweight='bold')
ax2.set_xlabel('Test Image Index', color='white')
ax2.set_ylabel('Confidence', color='white')
ax2.legend(facecolor='#1e293b', edgecolor='#334155', labelcolor='white', fontsize=8)

# 3. Grasp error distribution
ax3 = fig.add_subplot(gs[0, 2])
style_ax(ax3)
ax3.hist(grasp_errs, bins=8, color='#b66dff', edgecolor='white', linewidth=0.5, alpha=0.9)
ax3.axvline(np.mean(grasp_errs), color='white', lw=2, linestyle='--',
            label=f'Mean={np.mean(grasp_errs):.3f}')
ax3.set_title('Grasp Centre Error (Norm)', color='white', fontweight='bold')
ax3.set_xlabel('L2 Error (normalised)', color='white')
ax3.legend(facecolor='#1e293b', edgecolor='#334155', labelcolor='white', fontsize=8)

# 4. Predicted grasp positions
ax4 = fig.add_subplot(gs[1, 0])
style_ax(ax4)
gxs = [r['grasp'][0] for r in test_results]
gys = [r['grasp'][1] for r in test_results]
sc  = ax4.scatter(gxs, gys, c=conf_scores, cmap='RdYlGn', s=80,
                   edgecolors='white', linewidths=0.8, vmin=0, vmax=1)
plt.colorbar(sc, ax=ax4, label='Confidence')
ax4.set_xlim(0, 1); ax4.set_ylim(0, 1)
ax4.set_title('Predicted Grasp Positions', color='white', fontweight='bold')
ax4.set_xlabel('Grasp X (norm)', color='white')
ax4.set_ylabel('Grasp Y (norm)', color='white')

# 5. Metrics summary table
ax5 = fig.add_subplot(gs[1, 1])
ax5.set_facecolor('#111827')
ax5.axis('off')
metrics = [
    ['Metric', 'Value', 'Target'],
    ['mIoU', f'{mean_iou:.3f}', '> 0.40'],
    ['AP@0.25', f'{ap25*100:.0f}%', '> 60%'],
    ['AP@0.50', f'{ap50*100:.0f}%', '> 40%'],
    ['Avg Conf', f'{np.mean(conf_scores):.3f}', '> 0.50'],
    ['Grasp Err', f'{np.mean(grasp_errs):.3f}', '< 0.15'],
    ['Attempt %', f'{n_attempts/len(test_results)*100:.0f}%', '> 70%'],
]
table = ax5.table(cellText=metrics[1:], colLabels=metrics[0],
                  cellLoc='center', loc='center', bbox=[0, 0, 1, 1])
table.auto_set_font_size(False)
table.set_fontsize(10)
for (row, col), cell in table.get_celld().items():
    cell.set_facecolor('#1e293b' if row > 0 else '#334155')
    cell.set_text_props(color='white')
    cell.set_edgecolor('#334155')
ax5.set_title('Performance Metrics', color='white', fontweight='bold', pad=20)

# 6. Robot workspace mapping
ax6 = fig.add_subplot(gs[1, 2])
style_ax(ax6)
# Map normalised grasp coords to robot workspace (metres)
robot_xs = [0.25 + r['grasp'][0] * 0.50 for r in test_results]  # 0.25–0.75m
robot_ys = [-0.25 + r['grasp'][1] * 0.50 for r in test_results] # -0.25–0.25m
robot_z  = [0.05 + r['grasp'][2] * 0.20 for r in test_results]  # 0.05–0.25m
sc2 = ax6.scatter(robot_xs, robot_ys, c=robot_z, cmap='plasma',
                   s=80, edgecolors='white', linewidths=0.8)
plt.colorbar(sc2, ax=ax6, label='Z height (m)')
ax6.set_xlabel('X_robot (m)', color='white')
ax6.set_ylabel('Y_robot (m)', color='white')
ax6.set_title('Robot Workspace Grasp Points', color='white', fontweight='bold')

plt.show()

print('\n' + '='*55)
print('  NeurOGrasp — Final Performance Summary')
print('='*55)
print(f'  Dataset            : {len(pairs)} real transparent glass images')
print(f'  Architecture       : SNN (LIF) + Temporal Attention')
print(f'  Parameters         : {sum(p.numel() for p in model.parameters()):,}')
print(f'  mIoU (test)        : {mean_iou:.3f}')
print(f'  AP@0.5  (test)     : {ap50:.3f}')
print(f'  Avg confidence     : {np.mean(conf_scores):.3f}')
print(f'  Grasp centre error : {np.mean(grasp_errs)*H_tgt:.1f}px')
print(f'  Grasp attempt rate : {n_attempts/len(test_results)*100:.0f}%')
print(f'  Best val loss      : {best_val:.4f}')
print('='*55)
print('\nNext Steps:')
print('  1. Increase training data via augmentation (TRAIN_SIZE × 10)')
print('  2. Use real DVS event camera (Prophesee EVK4, DAVIS346)')
print('  3. Add depth estimation head for full 6-DOF grasp')
print('  4. Deploy on Intel Loihi neuromorphic chip for <1ms inference')
print('  5. Integrate with ROS2 for real robot arm control')